// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKao86Dwe9S9iJv5CH4HYnlK444N7w8Uo',
    appId: '1:553594413263:web:72ac7737b606134a3c97ba',
    messagingSenderId: '553594413263',
    projectId: 'app-ratebooks',
    authDomain: 'app-ratebooks.firebaseapp.com',
    storageBucket: 'app-ratebooks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3PNOIRXsog3HQlWRIrLLm1ahXeodEpOw',
    appId: '1:553594413263:android:4e7e7dd4b5b245473c97ba',
    messagingSenderId: '553594413263',
    projectId: 'app-ratebooks',
    storageBucket: 'app-ratebooks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSWGLLSed_E5zirvwDqzZU2OFUe5DYbyw',
    appId: '1:553594413263:ios:373ac0c87dc91ac33c97ba',
    messagingSenderId: '553594413263',
    projectId: 'app-ratebooks',
    storageBucket: 'app-ratebooks.firebasestorage.app',
    iosBundleId: 'com.example.trabDezani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSWGLLSed_E5zirvwDqzZU2OFUe5DYbyw',
    appId: '1:553594413263:ios:373ac0c87dc91ac33c97ba',
    messagingSenderId: '553594413263',
    projectId: 'app-ratebooks',
    storageBucket: 'app-ratebooks.firebasestorage.app',
    iosBundleId: 'com.example.trabDezani',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKao86Dwe9S9iJv5CH4HYnlK444N7w8Uo',
    appId: '1:553594413263:web:e12a27b4d4eca7ba3c97ba',
    messagingSenderId: '553594413263',
    projectId: 'app-ratebooks',
    authDomain: 'app-ratebooks.firebaseapp.com',
    storageBucket: 'app-ratebooks.firebasestorage.app',
  );

}